### ISSUE TITLE
Link to objection to `like` and `not_like`

### ISSUE THREAD

**Issue by gerrywastaken** [ReneB/activerecord-like#12]
Any chance of updating the Readme where it says

> Most of the code was previously in Active Record master, but was subsequently removed due to, amongst other, scope creep.

It took me a while to find this conversation and I'm sure it would be handy for others:

https://github.com/rails/rails/commit/8d02afeaee8993bd0fde69687fdd9bf30921e805

**Comment by ReneB** [comment]
Seems like a very sensible request, so I just added it to the README.
