### ISSUE TITLE
Support rails 8.0 & release new version (Working fork included in case this repo is unmaintained)

### ISSUE THREAD

**Issue by PikachuEXE** [ReneB/activerecord-like#21]
Already got the fork working for rails 7.2 & 8.0 with CI

https://github.com/PikachuEXE/activerecord-like

**Comment by ReneB** [comment]
It is not truly unmaintained, but I regrettably haven't worked with Ruby / Rails in a professional capacity for years now. And for years, you've done the brunt of the work updating this gem to newer versions of ActiveRecord. Would you be open to taking over this repo and the gem on rubygems.org? If so, I will see what it takes to transfer the ownership to you.

If you are not open to doing so, I will see whether I can merge your updates into this repo and cut a new gem, but it might take me a couple of days - or realistically, with the holidays coming up, weeks - before I get around to it.

**Comment by PikachuEXE** [comment]
I am open to maintaining this gem (I am doing the same for quite a few
Most of them I am using (except https://github.com/AssetSync/asset_sync which I moved away but still maintaining

**Comment by ReneB** [comment]
Thank you so much! I think any library is much better served by someone who actually uses it themselves, so I think it's best to pass it onto you. I assume [this](https://rubygems.org/profiles/PikachuEXE) is you, then?

**Comment by PikachuEXE** [comment]
Yes it is

**Comment by ReneB** [comment]
I think I see you've already released the new version to rubygems.org, I think? Is there anything else I can do to facilitate this transfer?

**Comment by PikachuEXE** [comment]
What else need to be done? Nothing? (I see you already updated README

Usually (previous experience) repo owner just add me as gem owner and repo collaborator and that's it

**Comment by ReneB** [comment]
I've invited you as a repo collaborator now as well. Feel free to either keep this one as the canonical repository, or change the settings in the gemspec to have it point to yours - whichever you prefer.

Thank you for taking over maintenance / ownership of the gem! I am happy that a small effort from years ago to preserve something I thought worthwhile has proven to be so, enough that you see fit to maintain it 🫶

**Comment by PikachuEXE** [comment]
231,686 downloads isn't small

Also just realize that my [rspec-json_matchers](https://rubygems.org/gems/rspec-json_matchers) got 774,553 downloads (totally was writing it for in-house use, didn't check until now)
You never know what sticks!

Anyway closing it now since new version released

**Comment by PikachuEXE** [comment]
Seeing what projects like https://github.com/railsadminteam/rails_admin & https://github.com/CanCanCommunity/cancancan did
What do you think about moving this project to an organization so only new members/collaborators need to be added?

**Comment by ReneB** [comment]
That sounds really reasonable! I'd say, go right ahead and do so. If there's anything you need from me in order to do so, let me know and I'll see what I can do 👍.

**Comment by PikachuEXE** [comment]
I can create organization but moving the repo is something I can't do

If you want to create organization along with moving the repo the naming can be something like
- `ActiveRecordLike` (if follow https://github.com/AssetSync/asset_sync)
- `activerecordliketeam` (if follow https://github.com/railsadminteam/rails_admin)
- Anything that's reasonable 
- 
- For my fork of `data_uri` organization I added `-ruby` suffix to avoid confusion https://github.com/data-uri-ruby/data_uri, though suffix probably not needed for this)

**Comment by ReneB** [comment]
Seems like that worked as well! I think I made you a member of the new organization as well, which you'll probably need to accept before I can give you a specific (admin?) role?

**Comment by PikachuEXE** [comment]
Joined~

**Comment by ReneB** [comment]
Aaaaaand you're the co-owner of the organization now 😄.

**Comment by PikachuEXE** [comment]
Commits merged back to `master`, gemspec updated
